import { SecurityUser, User, AdminMessage, Notice, AppConfig, ActivityCategory, GradeThreshold, Benefit, Activity, DashboardStats } from '../types';

// Mock Security Users
export const mockSecurityUsers: SecurityUser[] = [
  {
    id: 'sec-1',
    generatedId: 'SEC-10001',
    role: 'security',
    name: 'আব্দুল করিম',
    phone: '01711111111',
    email: 'karim@security.gov.bd',
    assignedArea: 'ঢাকা - মিরপুর',
    district: 'ঢাকা',
    nidLinked: true,
    createdAt: '2024-01-15T10:00:00Z',
    banned: false,
    redMarked: false,
  },
  {
    id: 'sec-2',
    generatedId: 'SEC-10002',
    role: 'security',
    name: 'ফাতেমা বেগম',
    phone: '01722222222',
    email: 'fatema@security.gov.bd',
    assignedArea: 'চট্টগ্রাম - আগ্রাবাদ',
    district: 'চট্টগ্রাম',
    nidLinked: true,
    createdAt: '2024-01-20T10:00:00Z',
    banned: false,
    redMarked: false,
  },
  {
    id: 'sec-3',
    generatedId: 'SEC-10003',
    role: 'security',
    name: 'মোহাম্মদ রহিম',
    phone: '01733333333',
    assignedArea: 'সিলেট - জিন্দাবাজার',
    district: 'সিলেট',
    nidLinked: true,
    createdAt: '2024-02-01T10:00:00Z',
    banned: false,
    redMarked: true,
  },
  {
    id: 'sec-4',
    generatedId: 'SEC-10004',
    role: 'security',
    name: 'নাসরিন আক্তার',
    phone: '01744444444',
    email: 'nasrin@security.gov.bd',
    assignedArea: 'রাজশাহী - বোয়ালিয়া',
    district: 'রাজশাহী',
    nidLinked: true,
    createdAt: '2024-02-10T10:00:00Z',
    banned: false,
    redMarked: false,
  },
  {
    id: 'sec-5',
    generatedId: 'SEC-10005',
    role: 'security',
    name: 'জাহিদ হাসান',
    phone: '01755555555',
    assignedArea: 'খুলনা - খালিশপুর',
    district: 'খুলনা',
    nidLinked: true,
    createdAt: '2024-02-15T10:00:00Z',
    banned: true,
    banExpiry: '2024-03-15T10:00:00Z',
    redMarked: false,
  },
];

// Mock General Users
export const mockGeneralUsers: User[] = Array.from({ length: 50 }, (_, i) => ({
  id: `user-${i + 1}`,
  role: 'user' as const,
  name: `ব্যবহারকারী ${i + 1}`,
  phone: `0171${String(i + 1).padStart(7, '0')}`,
  email: i % 3 === 0 ? `user${i + 1}@example.com` : undefined,
  district: ['ঢাকা', 'চট্টগ্রাম', 'সিলেট', 'রাজশাহী', 'খুলনা', 'বরিশাল'][i % 6],
  nidLinked: i % 4 !== 0,
  createdAt: new Date(2024, 0, 1 + i).toISOString(),
  banned: i % 20 === 0,
  banExpiry: i % 20 === 0 ? new Date(2024, 3, 1).toISOString() : undefined,
  redMarked: i % 15 === 0,
  points: Math.floor(Math.random() * 600),
  level: Math.floor(Math.random() * 10) + 1,
  grade: ['A+', 'A', 'B+', 'B', 'C'][Math.floor(Math.random() * 5)],
}));

// Mock Admin Messages
export const mockAdminMessages: AdminMessage[] = [
  {
    id: 'msg-1',
    fromUserId: 'sec-1',
    fromUserName: 'আব্দুল করিম',
    fromUserRole: 'security',
    subject: 'কার্যক্রম মুছে ফেলার অনুরোধ',
    body: 'একটি ভুল কার্যক্রম জমা দেওয়া হয়েছে। অনুগ্রহ করে এটি মুছে ফেলুন।',
    linkedSubmissionId: 'sub-123',
    type: 'delete_request',
    status: 'unread',
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'msg-2',
    fromUserId: 'sec-2',
    fromUserName: 'ফাতেমা বেগম',
    fromUserRole: 'security',
    subject: 'সন্দেহজনক কার্যক্রম রিপোর্ট',
    body: 'একজন ব্যবহারকারী একই ছবি একাধিকবার জমা দিচ্ছেন।',
    type: 'report',
    status: 'read',
    createdAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'msg-3',
    fromUserId: 'sec-3',
    fromUserName: 'মোহাম্মদ রহিম',
    fromUserRole: 'security',
    subject: 'পয়েন্ট সিস্টেম সম্পর্কে প্রশ্ন',
    body: 'নদী পরিষ্কারের জন্য পয়েন্ট কত হওয়া উচিত?',
    type: 'general',
    status: 'resolved',
    createdAt: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    resolvedAt: new Date(Date.now() - 20 * 60 * 60 * 1000).toISOString(),
    adminReply: 'নদী পরিষ্কারের জন্য ২৫ পয়েন্ট নির্ধারিত আছে।',
  },
  {
    id: 'msg-4',
    fromUserId: 'sec-4',
    fromUserName: 'নাসরিন আক্তার',
    fromUserRole: 'security',
    subject: 'এলাকা পরিবর্তনের অনুরোধ',
    body: 'আমার নির্ধারিত এলাকা পরিবর্তন করার প্রয়োজন।',
    type: 'general',
    status: 'unread',
    createdAt: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'msg-5',
    fromUserId: 'sec-1',
    fromUserName: 'আব্দুল করিম',
    fromUserRole: 'security',
    subject: 'ডুপ্লিকেট জমা রিপোর্ট',
    body: 'একই গাছ লাগানোর ছবি তিনবার জমা দেওয়া হয়েছে।',
    linkedSubmissionId: 'sub-456',
    type: 'report',
    status: 'read',
    createdAt: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'msg-6',
    fromUserId: 'sec-2',
    fromUserName: 'ফাতেমা বেগম',
    fromUserRole: 'security',
    subject: 'অ্যাপ ত্রুটি রিপোর্ট',
    body: 'ছবি আপলোড করার সময় অ্যাপ ক্র্যাশ হচ্ছে।',
    type: 'report',
    status: 'unread',
    createdAt: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'msg-7',
    fromUserId: 'sec-5',
    fromUserName: 'জাহিদ হাসান',
    fromUserRole: 'security',
    subject: 'ব্যান সম্পর্কে আপিল',
    body: 'আমার ব্যান তুলে নেওয়ার জন্য অনুরোধ করছি।',
    type: 'general',
    status: 'read',
    createdAt: new Date(Date.now() - 48 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'msg-8',
    fromUserId: 'sec-3',
    fromUserName: 'মোহাম্মদ রহিম',
    fromUserRole: 'security',
    subject: 'নতুন বেনিফিট যোগ করার প্রস্তাব',
    body: 'স্থানীয় হাসপাতালের সাথে চুক্তি করা যায় কিনা?',
    type: 'general',
    status: 'unread',
    createdAt: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'msg-9',
    fromUserId: 'sec-4',
    fromUserName: 'নাসরিন আক্তার',
    fromUserRole: 'security',
    subject: 'ভুল পয়েন্ট প্রদান',
    body: 'একটি কার্যক্রমে ভুল পয়েন্ট দেওয়া হয়েছে।',
    linkedSubmissionId: 'sub-789',
    type: 'delete_request',
    status: 'unread',
    createdAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
  },
  {
    id: 'msg-10',
    fromUserId: 'sec-1',
    fromUserName: 'আব্দুল করিম',
    fromUserRole: 'security',
    subject: 'প্রশিক্ষণ সামগ্রী অনুরোধ',
    body: 'নতুন সিকিউরিটি ব্যবহারকারীদের জন্য প্রশিক্ষণ ম্যানুয়াল প্রয়োজন।',
    type: 'general',
    status: 'resolved',
    createdAt: new Date(Date.now() - 72 * 60 * 60 * 1000).toISOString(),
    resolvedAt: new Date(Date.now() - 60 * 60 * 60 * 1000).toISOString(),
    adminReply: 'প্রশিক্ষণ ম্যানুয়াল শীঘ্রই পাঠানো হবে।',
  },
];

// Mock Notices
export const mockNotices: Notice[] = [
  {
    id: 'notice-1',
    title: 'নতুন পয়েন্ট সিস্টেম আপডেট',
    body: 'আগামীকাল থেকে নতুন পয়েন্ট সিস্টেম কার্যকর হবে। গাছ লাগানোর জন্য এখন ২৫ পয়েন্ট পাওয়া যাবে।',
    priority: 'important',
    recipients: 'all_users',
    sentAt: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    readCount: 342,
  },
  {
    id: 'notice-2',
    title: 'সিকিউরিটি ব্যবহারকারীদের জন্য প্রশিক্ষণ',
    body: 'আগামী শুক্রবার সকাল ১০টায় অনলাইন প্রশিক্ষণ সেশন অনুষ্ঠিত হবে।',
    priority: 'urgent',
    recipients: 'all_security',
    sentAt: new Date(Date.now() - 48 * 60 * 60 * 1000).toISOString(),
    readCount: 5,
  },
  {
    id: 'notice-3',
    title: 'অ্যাপ রক্ষণাবেক্ষণ',
    body: 'আগামীকাল রাত ১২টা থেকে ২টা পর্যন্ত অ্যাপ রক্ষণাবেক্ষণের জন্য বন্ধ থাকবে।',
    priority: 'important',
    recipients: 'all_users',
    sentAt: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
    readCount: 567,
  },
  {
    id: 'notice-4',
    title: 'ঢাকা জেলার ব্যবহারকারীদের জন্য বিশেষ চ্যালেঞ্জ',
    body: 'এই মাসে ঢাকা জেলার ব্যবহারকারীরা অতিরিক্ত ৫০ পয়েন্ট বোনাস পাবেন।',
    priority: 'normal',
    recipients: 'district',
    recipientDistrict: 'ঢাকা',
    sentAt: new Date(Date.now() - 72 * 60 * 60 * 1000).toISOString(),
    readCount: 123,
  },
  {
    id: 'notice-5',
    title: 'নতুন বেনিফিট যোগ করা হয়েছে',
    body: 'এখন থেকে স্বাস্থ্য সেবা এবং শিক্ষা সহায়তা বেনিফিট পাওয়া যাবে।',
    priority: 'normal',
    recipients: 'all_users',
    sentAt: new Date(Date.now() - 120 * 60 * 60 * 1000).toISOString(),
    readCount: 789,
  },
];

// Mock Activity Categories
export const mockCategories: ActivityCategory[] = [
  {
    id: 'cat-1',
    nameBn: 'গাছ লাগানো',
    nameEn: 'Tree Planting',
    icon: '🌳',
    basePoints: 20,
    bonusConditions: [
      { type: 'quantity', multiplier: 1.5, description: '5+ trees' },
      { type: 'location', multiplier: 1.2, description: 'Public area' },
    ],
    active: true,
  },
  {
    id: 'cat-2',
    nameBn: 'পরিষ্কার-পরিচ্ছন্নতা',
    nameEn: 'Cleaning',
    icon: '🧹',
    basePoints: 15,
    bonusConditions: [
      { type: 'time', multiplier: 1.3, description: 'Weekend' },
    ],
    active: true,
  },
  {
    id: 'cat-3',
    nameBn: 'নদী পরিষ্কার',
    nameEn: 'River Cleanup',
    icon: '🌊',
    basePoints: 25,
    bonusConditions: [
      { type: 'quantity', multiplier: 2.0, description: 'Group activity (5+ people)' },
    ],
    active: true,
  },
  {
    id: 'cat-4',
    nameBn: 'বর্জ্য ব্যবস্থাপনা',
    nameEn: 'Waste Management',
    icon: '♻️',
    basePoints: 10,
    bonusConditions: [],
    active: true,
  },
  {
    id: 'cat-5',
    nameBn: 'সচেতনতা কার্যক্রম',
    nameEn: 'Awareness Campaign',
    icon: '📢',
    basePoints: 15,
    bonusConditions: [
      { type: 'quantity', multiplier: 1.5, description: '20+ participants' },
    ],
    active: true,
  },
  {
    id: 'cat-6',
    nameBn: 'এনজিও কার্যক্রম',
    nameEn: 'NGO Activity',
    icon: '🤝',
    basePoints: 30,
    bonusConditions: [],
    active: true,
  },
  {
    id: 'cat-7',
    nameBn: 'বন্যপ্রাণী সেবা',
    nameEn: 'Wildlife Care',
    icon: '🦜',
    basePoints: 20,
    bonusConditions: [
      { type: 'location', multiplier: 1.5, description: 'Protected area' },
    ],
    active: true,
  },
];

// Mock Grade Thresholds
export const mockGradeThresholds: GradeThreshold[] = [
  { grade: 'A+', minPoints: 500 },
  { grade: 'A', minPoints: 350, maxPoints: 499 },
  { grade: 'B+', minPoints: 250, maxPoints: 349 },
  { grade: 'B', minPoints: 150, maxPoints: 249 },
  { grade: 'C', minPoints: 50, maxPoints: 149 },
  { grade: 'D', minPoints: 0, maxPoints: 49 },
];

// Mock Benefits
export const mockBenefits: Benefit[] = [
  {
    id: 'ben-1',
    titleBn: 'স্বাস্থ্য সেবা',
    titleEn: 'Health Service',
    descriptionBn: 'স্থানীয় হাসপাতালে বিনামূল্যে চেকআপ',
    descriptionEn: 'Free checkup at local hospital',
    requiredPoints: 200,
    requiredGrade: 'B+',
    category: 'health',
    active: true,
  },
  {
    id: 'ben-2',
    titleBn: 'শিক্ষা সহায়তা',
    titleEn: 'Education Support',
    descriptionBn: 'বিনামূল্যে বই এবং স্টেশনারি',
    descriptionEn: 'Free books and stationery',
    requiredPoints: 150,
    requiredGrade: 'B',
    category: 'education',
    active: true,
  },
  {
    id: 'ben-3',
    titleBn: 'পরিবহন ছাড়',
    titleEn: 'Transport Discount',
    descriptionBn: 'বাস ভাড়ায় ২০% ছাড়',
    descriptionEn: '20% discount on bus fare',
    requiredPoints: 100,
    requiredGrade: 'C',
    category: 'transport',
    active: true,
  },
  {
    id: 'ben-4',
    titleBn: 'খাদ্য সহায়তা',
    titleEn: 'Food Support',
    descriptionBn: 'মাসিক খাদ্য প্যাকেজ',
    descriptionEn: 'Monthly food package',
    requiredPoints: 300,
    requiredGrade: 'A',
    category: 'food',
    active: true,
  },
  {
    id: 'ben-5',
    titleBn: 'প্রশিক্ষণ কর্মসূচি',
    titleEn: 'Training Program',
    descriptionBn: 'বিনামূল্যে দক্ষতা উন্নয়ন প্রশিক্ষণ',
    descriptionEn: 'Free skill development training',
    requiredPoints: 400,
    requiredGrade: 'A',
    category: 'training',
    active: true,
  },
];

// Mock App Config
export const mockAppConfig: AppConfig = {
  categories: mockCategories,
  gradeThresholds: mockGradeThresholds,
  maxDailySubmissions: 5,
  submissionCooldownMinutes: 30,
  benefits: mockBenefits,
};

// Mock Dashboard Stats
export const mockDashboardStats: DashboardStats = {
  totalUsers: 50,
  totalSecurityUsers: 5,
  submissionsToday: 23,
  submissionsWeek: 156,
  submissionsMonth: 678,
  totalPointsDistributed: 12450,
  pendingReviews: 8,
  flaggedItems: 3,
  activeChallenges: 4,
};

// Mock Submissions for linked messages
export const mockSubmissions: Activity[] = [
  {
    id: 'sub-123',
    userId: 'user-5',
    categoryId: 'cat-1',
    title: 'গাছ লাগানো',
    description: 'পার্কে ৩টি গাছ লাগানো হয়েছে',
    imageUrl: 'https://via.placeholder.com/300',
    location: { lat: 23.8103, lng: 90.4125, address: 'মিরপুর, ঢাকা' },
    points: 20,
    status: 'approved',
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'sub-456',
    userId: 'user-12',
    categoryId: 'cat-2',
    title: 'পরিষ্কার-পরিচ্ছন্নতা',
    description: 'রাস্তা পরিষ্কার করা হয়েছে',
    imageUrl: 'https://via.placeholder.com/300',
    location: { lat: 22.3569, lng: 91.7832, address: 'আগ্রাবাদ, চট্টগ্রাম' },
    points: 15,
    status: 'pending',
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'sub-789',
    userId: 'user-23',
    categoryId: 'cat-3',
    title: 'নদী পরিষ্কার',
    description: 'নদী থেকে প্লাস্টিক সংগ্রহ',
    imageUrl: 'https://via.placeholder.com/300',
    location: { lat: 24.3745, lng: 88.6042, address: 'বোয়ালিয়া, রাজশাহী' },
    points: 25,
    status: 'approved',
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
];
